"""Initial migration

Revision ID: 09022e5d164e
Revises: 
Create Date: 2026-08-17 00:35:05.022477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09022e5d164e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandi_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('moving_average_7d', sa.Float(), nullable=True),
    sa.Column('percent_change_7d', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_commodity_market_date', 'mandi_prices', ['commodity', 'market', 'date'], unique=False)
    op.create_index(op.f('ix_mandi_prices_commodity'), 'mandi_prices', ['commodity'], unique=False)
    op.create_index(op.f('ix_mandi_prices_date'), 'mandi_prices', ['date'], unique=False)
    op.create_index(op.f('ix_mandi_prices_id'), 'mandi_prices', ['id'], unique=False)
    op.create_index(op.f('ix_mandi_prices_market'), 'mandi_prices', ['market'], unique=False)
    op.create_table('weather_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('rain', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_district_date', 'weather_logs', ['district', 'date'], unique=False)
    op.create_index(op.f('ix_weather_logs_date'), 'weather_logs', ['date'], unique=False)
    op.create_index(op.f('ix_weather_logs_district'), 'weather_logs', ['district'], unique=False)
    op.create_index(op.f('ix_weather_logs_id'), 'weather_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_logs_id'), table_name='weather_logs')
    op.drop_index(op.f('ix_weather_logs_district'), table_name='weather_logs')
    op.drop_index(op.f('ix_weather_logs_date'), table_name='weather_logs')
    op.drop_index('idx_district_date', table_name='weather_logs')
    op.drop_table('weather_logs')
    op.drop_index(op.f('ix_mandi_prices_market'), table_name='mandi_prices')
    op.drop_index(op.f('ix_mandi_prices_id'), table_name='mandi_prices')
    op.drop_index(op.f('ix_mandi_prices_date'), table_name='mandi_prices')
    op.drop_index(op.f('ix_mandi_prices_commodity'), table_name='mandi_prices')
    op.drop_index('idx_commodity_market_date', table_name='mandi_prices')
    op.drop_table('mandi_prices')
    # ### end Alembic commands ###
